# Generated by Django 4.1.1 on 2022-12-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
