version: '3.9'

services:
  web_db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: 'store'
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - web_db
volumes:
  postgres_data: